namespace Marketplace_InBrowser_Tests
{
    public class Marketplace_TestData_TextQuery_Category
    {
        public static IEnumerable<object[]> MyData =>
            new List<object[]>
            {
		new object[] {"textquery", "Category", "Air Compressing", 0, 2, 21 },
		new object[] {"textquery", "Category", "Analytics", 1, 12, 21 },
		new object[] {"textquery", "Category", "Analytics Lifecycle", 2, 1, 21 },
		new object[] {"textquery", "Category", "APS", 3, 4, 21 },
		new object[] {"textquery", "Category", "Asset Health", 4, 5, 21 },
		new object[] {"textquery", "Category", "Asset Monitoring", 5, 8, 21 },
		new object[] {"textquery", "Category", "Asset Optimization", 6, 5, 21 },
		new object[] {"textquery", "Category", "Asset Performance Management", 7, 6, 21 },
		new object[] {"textquery", "Category", "Augmented Reality", 8, 4, 21 },
		new object[] {"textquery", "Category", "Blowing", 9, 2, 21 },
		new object[] {"textquery", "Category", "Chilling", 10, 2, 21 },
		new object[] {"textquery", "Category", "CNC Monitoring", 11, 3, 21 },
		new object[] {"textquery", "Category", "Communications", 12, 1, 21 },
		new object[] {"textquery", "Category", "Continuous Improvement", 13, 8, 21 },
		new object[] {"textquery", "Category", "Continuous Manufacturing Intelligence", 14, 2, 21 },
		new object[] {"textquery", "Category", "Continuous Monitoring", 15, 5, 21 },
		new object[] {"textquery", "Category", "Continuous Supply Chain Intelligence", 16, 5, 21 },
		new object[] {"textquery", "Category", "Cost of Quality", 17, 3, 21 },
		new object[] {"textquery", "Category", "Data Analytics", 18, 4, 21 },
		new object[] {"textquery", "Category", "Data Collection", 19, 5, 21 },
		new object[] {"textquery", "Category", "Data Management", 20, 9, 21 },
		new object[] {"textquery", "Category", "Digital Manufacturing", 21, 5, 21 },
		new object[] {"textquery", "Category", "Digitized Quality Checks", 22, 2, 21 },
		new object[] {"textquery", "Category", "Edge Computing", 23, 5, 21 },
		new object[] {"textquery", "Category", "Energy Efficiency", 24, 3, 21 },
		new object[] {"textquery", "Category", "Energy Monitoring", 25, 6, 21 },
		new object[] {"textquery", "Category", "Enterprise Data Management", 26, 4, 21 },
		new object[] {"textquery", "Category", "Enterprise Integration", 27, 4, 21 },
		new object[] {"textquery", "Category", "Heating", 28, 2, 21 },
		new object[] {"textquery", "Category", "Historian", 29, 4, 21 },
		new object[] {"textquery", "Category", "IIoT", 30, 11, 21 },
		new object[] {"textquery", "Category", "In-House Quality Inspections", 31, 2, 21 },
		new object[] {"textquery", "Category", "Industrial Software", 32, 6, 21 },
		new object[] {"textquery", "Category", "Industry 4.0", 33, 7, 21 },
		new object[] {"textquery", "Category", "Inventory Management", 34, 3, 21 },
		new object[] {"textquery", "Category", "Inventory Optimization", 35, 4, 21 },
		new object[] {"textquery", "Category", "Logistics and Yard Solutions", 36, 2, 21 },
		new object[] {"textquery", "Category", "Machine Connectivity", 37, 4, 21 },
		new object[] {"textquery", "Category", "Machine Learning", 38, 9, 21 },
		new object[] {"textquery", "Category", "Machine Monitoring", 39, 4, 21 },
		new object[] {"textquery", "Category", "Machine Vision", 40, 3, 21 },
		new object[] {"textquery", "Category", "Machining", 41, 3, 21 },
		new object[] {"textquery", "Category", "Maintenance", 42, 11, 21 },
		new object[] {"textquery", "Category", "Manufacturing Operations Solutions", 43, 2, 21 },
		new object[] {"textquery", "Category", "Material Analysis Solutions", 44, 2, 21 },
		new object[] {"textquery", "Category", "Material Traceability", 45, 2, 21 },
		new object[] {"textquery", "Category", "MES", 46, 10, 21 },
		new object[] {"textquery", "Category", "Molding", 47, 2, 21 },
		new object[] {"textquery", "Category", "OEE", 48, 6, 21 },
		new object[] {"textquery", "Category", "OT Data Lake", 49, 2, 21 },
		new object[] {"textquery", "Category", "Palletizing", 50, 1, 21 },
		new object[] {"textquery", "Category", "Planning and Scheduling", 51, 2, 21 },
		new object[] {"textquery", "Category", "Plant Reliability", 52, 3, 21 },
		new object[] {"textquery", "Category", "Power Factor", 53, 4, 21 },
		new object[] {"textquery", "Category", "Power Quality", 54, 3, 21 },
		new object[] {"textquery", "Category", "Predictive Maintenance", 55, 8, 21 },
		new object[] {"textquery", "Category", "Process Optimization", 56, 7, 21 },
		new object[] {"textquery", "Category", "Product Quality", 57, 1, 21 },
		new object[] {"textquery", "Category", "Production Quality", 58, 1, 21 },
		new object[] {"textquery", "Category", "Quality Assessment", 59, 2, 21 },
		new object[] {"textquery", "Category", "Quality Assurance", 60, 6, 21 },
		new object[] {"textquery", "Category", "Quality Traceability", 61, 2, 21 },
		new object[] {"textquery", "Category", "Remote Monitoring", 62, 5, 21 },
		new object[] {"textquery", "Category", "Renewables Monitoring", 63, 2, 21 },
		new object[] {"textquery", "Category", "Short Interval Control", 64, 2, 21 },
		new object[] {"textquery", "Category", "Smart Manufacturing", 65, 7, 21 },
		new object[] {"textquery", "Category", "Supplier Inventory Visibility", 66, 2, 21 },
		new object[] {"textquery", "Category", "Supplier Quality", 67, 2, 21 },
		new object[] {"textquery", "Category", "Supply Chain", 68, 7, 21 },
		new object[] {"textquery", "Category", "Supply Chain Automation", 69, 2, 21 },
		new object[] {"textquery", "Category", "Supply Chain Management", 70, 2, 21 },
		new object[] {"textquery", "Category", "Supply Chain Optimization", 71, 5, 21 },
		new object[] {"textquery", "Category", "Warranty Management", 72, 1, 21 },
		new object[] {"textquery", "Category", "Workflow Mapping", 73, 3, 21 },
			};
    }
    public class Marketplace_TestData_TextQuery_Vertical
    {
        public static IEnumerable<object[]> MyData =>
            new List<object[]>
            {
		new object[] {"textquery", "Vertical", "Academia", 0, 4, 21 },
		new object[] {"textquery", "Vertical", "Aerospace", 1, 13, 21 },
		new object[] {"textquery", "Vertical", "Agriculture", 2, 6, 21 },
		new object[] {"textquery", "Vertical", "Assembly", 3, 3, 21 },
		new object[] {"textquery", "Vertical", "Automotive", 4, 14, 21 },
		new object[] {"textquery", "Vertical", "Biotechnology", 5, 1, 21 },
		new object[] {"textquery", "Vertical", "Building Materials and Supplies", 6, 4, 21 },
		new object[] {"textquery", "Vertical", "Cement", 7, 8, 21 },
		new object[] {"textquery", "Vertical", "Chemical", 8, 9, 21 },
		new object[] {"textquery", "Vertical", "CNC", 9, 8, 21 },
		new object[] {"textquery", "Vertical", "Consumer and Paper Goods", 10, 6, 21 },
		new object[] {"textquery", "Vertical", "Consumer Products", 11, 4, 21 },
		new object[] {"textquery", "Vertical", "Defense", 12, 8, 21 },
		new object[] {"textquery", "Vertical", "Discrete Manufacturing", 13, 7, 21 },
		new object[] {"textquery", "Vertical", "Distribution", 14, 7, 21 },
		new object[] {"textquery", "Vertical", "Electronics", 15, 5, 21 },
		new object[] {"textquery", "Vertical", "Energy", 16, 15, 21 },
		new object[] {"textquery", "Vertical", "Energy (Oil & Gas)", 17, 12, 21 },
		new object[] {"textquery", "Vertical", "Food & Beverage", 18, 9, 21 },
		new object[] {"textquery", "Vertical", "Forestry", 19, 4, 21 },
		new object[] {"textquery", "Vertical", "Foundry", 20, 4, 21 },
		new object[] {"textquery", "Vertical", "Government", 21, 9, 21 },
		new object[] {"textquery", "Vertical", "Greenhouses", 22, 3, 21 },
		new object[] {"textquery", "Vertical", "Heavy Industry", 23, 9, 21 },
		new object[] {"textquery", "Vertical", "Hospitality", 24, 3, 21 },
		new object[] {"textquery", "Vertical", "Industrial Gas", 25, 5, 21 },
		new object[] {"textquery", "Vertical", "Intelligence", 26, 12, 21 },
		new object[] {"textquery", "Vertical", "Life Sciences", 27, 5, 21 },
		new object[] {"textquery", "Vertical", "Lumber", 28, 5, 21 },
		new object[] {"textquery", "Vertical", "Machine Shops", 29, 7, 21 },
		new object[] {"textquery", "Vertical", "Manufacturing", 30, 16, 21 },
		new object[] {"textquery", "Vertical", "Medical Devices", 31, 3, 21 },
		new object[] {"textquery", "Vertical", "Metals", 32, 8, 21 },
		new object[] {"textquery", "Vertical", "Mining", 33, 11, 21 },
		new object[] {"textquery", "Vertical", "Packaging", 34, 4, 21 },
		new object[] {"textquery", "Vertical", "Personal Care", 35, 6, 21 },
		new object[] {"textquery", "Vertical", "Petrochemical", 36, 6, 21 },
		new object[] {"textquery", "Vertical", "Pharmaceuticals", 37, 6, 21 },
		new object[] {"textquery", "Vertical", "Plastics", 38, 7, 21 },
		new object[] {"textquery", "Vertical", "Plastics and Rubber", 39, 2, 21 },
		new object[] {"textquery", "Vertical", "Power", 40, 10, 21 },
		new object[] {"textquery", "Vertical", "Process Manufacturing", 41, 7, 21 },
		new object[] {"textquery", "Vertical", "Pulp & Paper", 42, 6, 21 },
		new object[] {"textquery", "Vertical", "Refining", 43, 6, 21 },
		new object[] {"textquery", "Vertical", "Remanufacturing", 44, 4, 21 },
		new object[] {"textquery", "Vertical", "Retailers", 45, 3, 21 },
		new object[] {"textquery", "Vertical", "Sawmills", 46, 5, 21 },
		new object[] {"textquery", "Vertical", "Seafood", 47, 3, 21 },
		new object[] {"textquery", "Vertical", "Semiconductor", 48, 7, 21 },
		new object[] {"textquery", "Vertical", "Small-Medium Enterprises", 49, 9, 21 },
		new object[] {"textquery", "Vertical", "Steel", 50, 9, 21 },
		new object[] {"textquery", "Vertical", "Telecom", 51, 5, 21 },
		new object[] {"textquery", "Vertical", "Textile", 52, 7, 21 },
		new object[] {"textquery", "Vertical", "Utilities", 53, 11, 21 },
			};
    }
    public class Marketplace_TestData_TextQuery_Publisher
    {
        public static IEnumerable<object[]> MyData =>
            new List<object[]>
            {
		new object[] {"textquery", "Publisher", "5G Technologies USA Ltd.", 0, 3, 21 },
		new object[] {"textquery", "Publisher", "Adapdix", 1, 1, 21 },
		new object[] {"textquery", "Publisher", "Amatrol", 2, 1, 21 },
		new object[] {"textquery", "Publisher", "Augury", 3, 1, 21 },
		new object[] {"textquery", "Publisher", "Beeond, Inc.", 4, 1, 21 },
		new object[] {"textquery", "Publisher", "C5MI Insight LLC", 5, 3, 21 },
		new object[] {"textquery", "Publisher", "CESMII - The Smart Manufacturing Institute", 6, 1, 21 },
		new object[] {"textquery", "Publisher", "CoreWatts", 7, 1, 21 },
		new object[] {"textquery", "Publisher", "Emerson", 8, 1, 21 },
		new object[] {"textquery", "Publisher", "Falkonry Inc.", 9, 1, 21 },
		new object[] {"textquery", "Publisher", "Litmus Automation", 10, 1, 21 },
		new object[] {"textquery", "Publisher", "SAS", 11, 2, 21 },
		new object[] {"textquery", "Publisher", "ShelfAware", 12, 1, 21 },
		new object[] {"textquery", "Publisher", "SymphonyAI Industrial", 13, 1, 21 },
		new object[] {"textquery", "Publisher", "ThinkIQ", 14, 1, 21 },
		new object[] {"textquery", "Publisher", "Toward Zero", 15, 1, 21 },
			};
    }
    public class Marketplace_TestData_Checkbox_Category
    {
        public static IEnumerable<object[]> MyData =>
            new List<object[]>
            {
		new object[] {"checkbox", "Category", "Air Compressing", 0, 2, 21 },
		new object[] {"checkbox", "Category", "Analytics", 1, 6, 21 },
		new object[] {"checkbox", "Category", "Analytics Lifecycle", 2, 1, 21 },
		new object[] {"checkbox", "Category", "APS", 3, 2, 21 },
		new object[] {"checkbox", "Category", "Asset Health", 4, 5, 21 },
		new object[] {"checkbox", "Category", "Asset Monitoring", 5, 8, 21 },
		new object[] {"checkbox", "Category", "Asset Optimization", 6, 5, 21 },
		new object[] {"checkbox", "Category", "Asset Performance Management", 7, 5, 21 },
		new object[] {"checkbox", "Category", "Augmented Reality", 8, 3, 21 },
		new object[] {"checkbox", "Category", "Blowing", 9, 2, 21 },
		new object[] {"checkbox", "Category", "Chilling", 10, 2, 21 },
		new object[] {"checkbox", "Category", "CNC Monitoring", 11, 3, 21 },
		new object[] {"checkbox", "Category", "Communications", 12, 1, 21 },
		new object[] {"checkbox", "Category", "Continuous Improvement", 13, 8, 21 },
		new object[] {"checkbox", "Category", "Continuous Manufacturing Intelligence", 14, 2, 21 },
		new object[] {"checkbox", "Category", "Continuous Monitoring", 15, 5, 21 },
		new object[] {"checkbox", "Category", "Continuous Supply Chain Intelligence", 16, 5, 21 },
		new object[] {"checkbox", "Category", "Cost of Quality", 17, 2, 21 },
		new object[] {"checkbox", "Category", "Data Analytics", 18, 4, 21 },
		new object[] {"checkbox", "Category", "Data Collection", 19, 5, 21 },
		new object[] {"checkbox", "Category", "Data Management", 20, 5, 21 },
		new object[] {"checkbox", "Category", "Digital Manufacturing", 21, 4, 21 },
		new object[] {"checkbox", "Category", "Digitized Quality Checks", 22, 2, 21 },
		new object[] {"checkbox", "Category", "Edge Computing", 23, 5, 21 },
		new object[] {"checkbox", "Category", "Energy Efficiency", 24, 3, 21 },
		new object[] {"checkbox", "Category", "Energy Monitoring", 25, 6, 21 },
		new object[] {"checkbox", "Category", "Enterprise Data Management", 26, 3, 21 },
		new object[] {"checkbox", "Category", "Enterprise Integration", 27, 4, 21 },
		new object[] {"checkbox", "Category", "Heating", 28, 2, 21 },
		new object[] {"checkbox", "Category", "Historian", 29, 2, 21 },
		new object[] {"checkbox", "Category", "IIoT", 30, 10, 21 },
		new object[] {"checkbox", "Category", "In-House Quality Inspections", 31, 2, 21 },
		new object[] {"checkbox", "Category", "Industrial Software", 32, 6, 21 },
		new object[] {"checkbox", "Category", "Industry 4.0", 33, 5, 21 },
		new object[] {"checkbox", "Category", "Inventory Management", 34, 3, 21 },
		new object[] {"checkbox", "Category", "Inventory Optimization", 35, 4, 21 },
		new object[] {"checkbox", "Category", "Logistics and Yard Solutions", 36, 2, 21 },
		new object[] {"checkbox", "Category", "Machine Connectivity", 37, 4, 21 },
		new object[] {"checkbox", "Category", "Machine Learning", 38, 8, 21 },
		new object[] {"checkbox", "Category", "Machine Monitoring", 39, 4, 21 },
		new object[] {"checkbox", "Category", "Machine Vision", 40, 2, 21 },
		new object[] {"checkbox", "Category", "Machining", 41, 3, 21 },
		new object[] {"checkbox", "Category", "Maintenance", 42, 6, 21 },
		new object[] {"checkbox", "Category", "Manufacturing Operations Solutions", 43, 2, 21 },
		new object[] {"checkbox", "Category", "Material Analysis Solutions", 44, 2, 21 },
		new object[] {"checkbox", "Category", "Material Traceability", 45, 2, 21 },
		new object[] {"checkbox", "Category", "MES", 46, 4, 21 },
		new object[] {"checkbox", "Category", "Molding", 47, 2, 21 },
		new object[] {"checkbox", "Category", "OEE", 48, 5, 21 },
		new object[] {"checkbox", "Category", "OT Data Lake", 49, 2, 21 },
		new object[] {"checkbox", "Category", "Palletizing", 50, 1, 21 },
		new object[] {"checkbox", "Category", "Planning and Scheduling", 51, 2, 21 },
		new object[] {"checkbox", "Category", "Plant Reliability", 52, 3, 21 },
		new object[] {"checkbox", "Category", "Power Factor", 53, 4, 21 },
		new object[] {"checkbox", "Category", "Power Quality", 54, 2, 21 },
		new object[] {"checkbox", "Category", "Predictive Maintenance", 55, 7, 21 },
		new object[] {"checkbox", "Category", "Process Optimization", 56, 7, 21 },
		new object[] {"checkbox", "Category", "Product Quality", 57, 1, 21 },
		new object[] {"checkbox", "Category", "Production Quality", 58, 1, 21 },
		new object[] {"checkbox", "Category", "Quality Assessment", 59, 2, 21 },
		new object[] {"checkbox", "Category", "Quality Assurance", 60, 6, 21 },
		new object[] {"checkbox", "Category", "Quality Traceability", 61, 2, 21 },
		new object[] {"checkbox", "Category", "Remote Monitoring", 62, 5, 21 },
		new object[] {"checkbox", "Category", "Renewables Monitoring", 63, 2, 21 },
		new object[] {"checkbox", "Category", "Short Interval Control", 64, 2, 21 },
		new object[] {"checkbox", "Category", "Smart Manufacturing", 65, 3, 21 },
		new object[] {"checkbox", "Category", "Supplier Inventory Visibility", 66, 2, 21 },
		new object[] {"checkbox", "Category", "Supplier Quality", 67, 2, 21 },
		new object[] {"checkbox", "Category", "Supply Chain", 68, 3, 21 },
		new object[] {"checkbox", "Category", "Supply Chain Automation", 69, 2, 21 },
		new object[] {"checkbox", "Category", "Supply Chain Management", 70, 2, 21 },
		new object[] {"checkbox", "Category", "Supply Chain Optimization", 71, 5, 21 },
		new object[] {"checkbox", "Category", "Warranty Management", 72, 1, 21 },
		new object[] {"checkbox", "Category", "Workflow Mapping", 73, 3, 21 },
			};
    }
    public class Marketplace_TestData_Checkbox_Vertical
    {
        public static IEnumerable<object[]> MyData =>
            new List<object[]>
            {
		new object[] {"checkbox", "Vertical", "Academia", 0, 4, 21 },
		new object[] {"checkbox", "Vertical", "Aerospace", 1, 13, 21 },
		new object[] {"checkbox", "Vertical", "Agriculture", 2, 6, 21 },
		new object[] {"checkbox", "Vertical", "Assembly", 3, 3, 21 },
		new object[] {"checkbox", "Vertical", "Automotive", 4, 14, 21 },
		new object[] {"checkbox", "Vertical", "Biotechnology", 5, 1, 21 },
		new object[] {"checkbox", "Vertical", "Building Materials and Supplies", 6, 4, 21 },
		new object[] {"checkbox", "Vertical", "Cement", 7, 7, 21 },
		new object[] {"checkbox", "Vertical", "Chemical", 8, 9, 21 },
		new object[] {"checkbox", "Vertical", "CNC", 9, 7, 21 },
		new object[] {"checkbox", "Vertical", "Consumer and Paper Goods", 10, 6, 21 },
		new object[] {"checkbox", "Vertical", "Consumer Products", 11, 4, 21 },
		new object[] {"checkbox", "Vertical", "Defense", 12, 8, 21 },
		new object[] {"checkbox", "Vertical", "Discrete Manufacturing", 13, 7, 21 },
		new object[] {"checkbox", "Vertical", "Distribution", 14, 6, 21 },
		new object[] {"checkbox", "Vertical", "Electronics", 15, 5, 21 },
		new object[] {"checkbox", "Vertical", "Energy", 16, 8, 21 },
		new object[] {"checkbox", "Vertical", "Energy (Oil & Gas)", 17, 12, 21 },
		new object[] {"checkbox", "Vertical", "Food & Beverage", 18, 9, 21 },
		new object[] {"checkbox", "Vertical", "Forestry", 19, 4, 21 },
		new object[] {"checkbox", "Vertical", "Foundry", 20, 4, 21 },
		new object[] {"checkbox", "Vertical", "Government", 21, 8, 21 },
		new object[] {"checkbox", "Vertical", "Greenhouses", 22, 3, 21 },
		new object[] {"checkbox", "Vertical", "Heavy Industry", 23, 9, 21 },
		new object[] {"checkbox", "Vertical", "Hospitality", 24, 3, 21 },
		new object[] {"checkbox", "Vertical", "Industrial Gas", 25, 5, 21 },
		new object[] {"checkbox", "Vertical", "Intelligence", 26, 3, 21 },
		new object[] {"checkbox", "Vertical", "Life Sciences", 27, 5, 21 },
		new object[] {"checkbox", "Vertical", "Lumber", 28, 5, 21 },
		new object[] {"checkbox", "Vertical", "Machine Shops", 29, 7, 21 },
		new object[] {"checkbox", "Vertical", "Manufacturing", 30, 8, 21 },
		new object[] {"checkbox", "Vertical", "Medical Devices", 31, 3, 21 },
		new object[] {"checkbox", "Vertical", "Metals", 32, 8, 21 },
		new object[] {"checkbox", "Vertical", "Mining", 33, 11, 21 },
		new object[] {"checkbox", "Vertical", "Packaging", 34, 4, 21 },
		new object[] {"checkbox", "Vertical", "Personal Care", 35, 6, 21 },
		new object[] {"checkbox", "Vertical", "Petrochemical", 36, 6, 21 },
		new object[] {"checkbox", "Vertical", "Pharmaceuticals", 37, 6, 21 },
		new object[] {"checkbox", "Vertical", "Plastics", 38, 7, 21 },
		new object[] {"checkbox", "Vertical", "Plastics and Rubber", 39, 2, 21 },
		new object[] {"checkbox", "Vertical", "Power", 40, 3, 21 },
		new object[] {"checkbox", "Vertical", "Process Manufacturing", 41, 7, 21 },
		new object[] {"checkbox", "Vertical", "Pulp & Paper", 42, 6, 21 },
		new object[] {"checkbox", "Vertical", "Refining", 43, 6, 21 },
		new object[] {"checkbox", "Vertical", "Remanufacturing", 44, 4, 21 },
		new object[] {"checkbox", "Vertical", "Retailers", 45, 3, 21 },
		new object[] {"checkbox", "Vertical", "Sawmills", 46, 5, 21 },
		new object[] {"checkbox", "Vertical", "Seafood", 47, 3, 21 },
		new object[] {"checkbox", "Vertical", "Semiconductor", 48, 7, 21 },
		new object[] {"checkbox", "Vertical", "Small-Medium Enterprises", 49, 9, 21 },
		new object[] {"checkbox", "Vertical", "Steel", 50, 9, 21 },
		new object[] {"checkbox", "Vertical", "Telecom", 51, 5, 21 },
		new object[] {"checkbox", "Vertical", "Textile", 52, 7, 21 },
		new object[] {"checkbox", "Vertical", "Utilities", 53, 11, 21 },
			};
    }
    public class Marketplace_TestData_Checkbox_Publisher
    {
        public static IEnumerable<object[]> MyData =>
            new List<object[]>
            {
		new object[] {"checkbox", "Publisher", "5G Technologies USA Ltd.", 0, 3, 21 },
		new object[] {"checkbox", "Publisher", "Adapdix", 1, 1, 21 },
		new object[] {"checkbox", "Publisher", "Amatrol", 2, 1, 21 },
		new object[] {"checkbox", "Publisher", "Augury", 3, 1, 21 },
		new object[] {"checkbox", "Publisher", "Beeond, Inc.", 4, 1, 21 },
		new object[] {"checkbox", "Publisher", "C5MI Insight LLC", 5, 3, 21 },
		new object[] {"checkbox", "Publisher", "CESMII - The Smart Manufacturing Institute", 6, 1, 21 },
		new object[] {"checkbox", "Publisher", "CoreWatts", 7, 1, 21 },
		new object[] {"checkbox", "Publisher", "Emerson", 8, 1, 21 },
		new object[] {"checkbox", "Publisher", "Falkonry Inc.", 9, 1, 21 },
		new object[] {"checkbox", "Publisher", "Litmus Automation", 10, 1, 21 },
		new object[] {"checkbox", "Publisher", "SAS", 11, 2, 21 },
		new object[] {"checkbox", "Publisher", "ShelfAware", 12, 1, 21 },
		new object[] {"checkbox", "Publisher", "SymphonyAI Industrial", 13, 1, 21 },
		new object[] {"checkbox", "Publisher", "ThinkIQ", 14, 1, 21 },
		new object[] {"checkbox", "Publisher", "Toward Zero", 15, 1, 21 },
			};
    }
}
