name: Stage|File Copy|TEST

on:
  #manually trigger deploy
  workflow_dispatch:

env:
  # set this to the path to your build output, defaults to the repository root
  BUILD_OUTPUT_DIRECTORY: './frontend/build'  
  WORKING_DIRECTORY: 'frontend'   
  # set this to the node version to use
  NODE_VERSION: '10.16.3'                

jobs:
  Build-and-Deploy-FrontEnd:
    name: 'Build and Deploy React front End'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'Build React Code - npm install, build'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        CI: '' #bypass treating-warnings-as-errors-because-process-env-ci-true 
      run: |
        # Build the project, then
        # deploy to Azure Web App.
        npm install
        npm run build:staging --if-present
    - name: 'Copy robots.Staging.txt into robots.txt'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: | 
        #copying robots.Staging.txt robots.txt 
        cp robots.Staging.txt robots.txt 
        #viewing file contents
        cat robots.txt
