name: Stage|File Copy|TEST

on:
  #manually trigger deploy
  workflow_dispatch:

env:
  # set this to the path to your build output, defaults to the repository root
  BUILD_OUTPUT_DIRECTORY: './frontend/build'  
  WORKING_DIRECTORY: 'frontend'   
  # set this to the node version to use
  NODE_VERSION: '10.16.3'                

jobs:
  Build-and-Deploy-FrontEnd:
    name: 'File Read me, copy test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'Show readme.MD'
      run: | 
        #GITHUB_WORKSPACE - ${{ env.GITHUB_WORKSPACE }}
        #GITHUB_PATH - ${{ env.GITHUB_PATH }}
        #GITHUB_ACTION_PATH - ${{ env.GITHUB_ACTION_PATH }}
        #dir
        dir
        echo 'robots.Staging.txt ---------------------------'
        cat frontend/robots.Staging.txt
        echo '---------------------------'
        echo '---------------------------'
        echo 'robots.txt ---------------------------'
        cat frontend/public/robots.txt
        echo '---------------------------'
        echo '---------------------------'
        echo 'copying robots.txt - staging ---------------------------'
        cp frontend/robots.Staging.txt frontend/public/robots.txt
        echo 'robots.txt - revised ---------------------------'
        cat frontend/public/robots.txt
        echo '---------------------------'
        echo '---------------------------'
        # Readme.md -------------------------
        #cat README.md
        # .env - 1 -------------------------
        #cat frontend/.env
        # .env - 2 -------------------------
        #cat frontend/.env
        #-----------------------------------
        echo '#GITHUB_WORKSPACE - ${{env.GITHUB_WORKSPACE}}'
