# This workflow will build and run In Browser Selenium Web Driver Tests
#
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: Test|In Browser|Marketplace
on: [workflow_dispatch]
  #manually trigger deploy
  #workflow_dispatch:
  # Trigger the workflow on push
  #push:
  #  branches:
  #    - develop
  #    - main
  #pull_request:
  #  branches:
  #    - develop
  #    - main

env:
  # set this to the path to your solution file
  SOLUTION_DIRECTORY: './'      
  # Solution file name
  SOLUTION_FILE: 'CESMII.Marketplace.sln'      
  # Set this to the path to your test project file
  PROJECT_DIRECTORY: './api/Tests/CESMII.Marketplace.InBrowser.Tests/'
  # Test project file to use
  PROJECT_NAME: 'CESMII.Marketplace.InBrowser.Tests'      
  # set this to the .NET core version to use
  NETCORE_VERSION: "6.0.x"

jobs:
  build:
    name: Test in Browser
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository so we can run our tests
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Test on project (${{env.PROJECT_NAME}})
        run: dotnet test ${{env.PROJECT_DIRECTORY}}${{env.PROJECT_NAME}}.csproj --configuration Staging --verbosity normal -l:"console;verbosity=normal"
        working-directory: ${{env.SOLUTION_DIRECTORY}}
