# This workflow will build and run In Browser Selenium Web Driver Tests
#
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: Test|In Browser|Marketplace
on:
  #manually trigger deploy
  workflow_dispatch:
  # Trigger the workflow on push
  #push:
  #  branches:
  #    - develop
  #    - main
  #pull_request:
  #  branches:
  #    - develop
  #    - main

env:
  # Flags that is set automatically to determine whether we 
  # are running on Github.com or within nektos/act (on Desktop).
  ONGITHUB: true

  # Main project path
  MARKETPLACE_PROJECT_DIRECTORY: './api/CESMII.Marketplace.API/'
  # Main project file name
  MARKETPLACE_PROJECT_FILE: 'CESMII.Marketplace.API.csproj'
  # Main project fqn
  MARKETPLACE_PROJECT_FQDN: './api/CESMII.Marketplace.API/CESMII.Marketplace.API.csproj'

  # set this to the .NET core version to use
  NETCORE_VERSION: "6.0.x"
  # set this to the NODE JS version to use
  NODEJS_VERSION: "16.17.0"
  # set this to npm working directory
  NPM_WORKING_DIRECTORY: 'frontend'

  # Access to our MongoDB
  MONGODB_DATABASE_NAME: "test"
  MOUNT_SOURCE_GITHUB: '/home/runner/work/Marketplace/Marketplace/mongo-data'  
  MOUNT_SOURCE_DESKTOP: 'c:/CESMII.github/Marketplace/mongo-data'

  # Networking Details
  MARKETPLACE_BRIDGE_CONNECTION: "http://XX.XX.XX.XX"
  MONGODB_LOCAL_CONNECTION: "mongodb://testuser:password@localhost:27017"
  MONGODB_BRIDGE_CONNECTION: "mongodb://XXXXX:XXXXX@XX.XX.XX.XX:27017"
  NODEJS_BRIDGE_CONNECTION: "http://XX.XX.XX.XX"


jobs:
  runner-job:
    runs-on: ubuntu-latest
    steps:
    # Automating the setting of a flag that helps resolves
    # differences between Github Actions on github.com and
    # using nektos/act on Windows using Docker Desktop.
    - name: 0__Platform-Portability - Running on Github Or Desktop? 
      if: github.actor == 'nektos/act'
      run: echo "ONGITHUB=false" >> $GITHUB_ENV

    - name: 1__Git-Repos-Checkout - Check out Marketplace Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    # Create bridge network for communication between containers
    - name: 2__Networking - Set up networking
      run: |
          docker network remove --force mysubnet1 ;
          docker network create mysubnet1 ;

    ############################################################
    # Run one of these two
    # Initialize a Mongo DB database (on Github)
    # Note: the "env" section seems not to work and so the -e switches are necessary
    - name: 3__MongoDB - Create MongoDB Docker container (On Github)
      if: env.ONGITHUB == 'true'
      run: docker run -d --name=MyMongoDB -p 27017:27017  --network mysubnet1 -e MONGO_INIT_DATABASE=test -e MONGO_INITDB_ROOT_USERNAME=testuser -e MONGO_INITDB_ROOT_PASSWORD=password --mount src="${{env.MOUNT_SOURCE_GITHUB}}",target=/data,type=bind mongo:6.0
      env:
         MONGO_INIT_DATABASE: test 
         MONGO_INITDB_ROOT_USERNAME: testuser
         MONGO_INITDB_ROOT_PASSWORD: password

    # Initialize a Mongo DB database (on the Desktop)
    - name: 4__MongoDB - Create MongoDB Docker container (On Desktop)
      if: env.ONGITHUB == 'false'
      run: docker run -d --name=MyMongoDB -p 27017:27017  --network mysubnet1 -e MONGO_INIT_DATABASE=test -e MONGO_INITDB_ROOT_USERNAME=testuser -e MONGO_INITDB_ROOT_PASSWORD=password --mount src="${{env.MOUNT_SOURCE_DESKTOP}}",target=/data,type=bind mongo:6.0
      env:
         MONGO_INIT_DATABASE: test 
         MONGO_INITDB_ROOT_USERNAME: testuser
         MONGO_INITDB_ROOT_PASSWORD: password
    ############################################################


    # Putting steps 6, 7 & 8 between "Create mongoDB container" and "Populate mongo database" 
    # seems to help the mongo container settle down so it can pass its tests
    - name: 5__Marketplace - Set up dotnet core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    # Marketplace API
    - name: 6__Marketplace - Restore dependencies (${{env.MARKETPLACE_PROJECT_FQDN}})
      run: dotnet restore ${{env.MARKETPLACE_PROJECT_FILE}}
      working-directory: ${{env.MARKETPLACE_PROJECT_DIRECTORY}}

    # Publish the app and the tests
    - name: 7__Marketplace - Publish Marketplace Api
      run: |
        dotnet publish --framework:net6.0 ${{env.MARKETPLACE_PROJECT_FQDN}} -c Release -o ./publish ;
        dotnet publish ./DumpAppLog/DumpAppLog.csproj

    # Create a Docker Container for Marketplace
    - name: 8__Marketplace - Build Docker Image CESMII.Marketplace.API
      run: docker build -f "./api/CESMII.Marketplace.API/Dockerfile" --force-rm -t cesmiimarketplaceapi:dev --target base  --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=CESMII.Marketplace.API" "./"

    # Populate mongo database - 
    - name: 9__MongoDB - Populate mongo database
      run: docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=app_log --file=/data/app_log.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=ExternalSource --file=/data/ExternalSource.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=JobLog --file=/data/JobLog.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=JobDefinition --file=/data/JobDefinition.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=LookupItem --file=/data/LookupItem.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=MarketplaceItem --file=/data/MarketplaceItem.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=MarketplaceItemAnalytics --file=/data/MarketplaceItemAnalytics.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=Organization --file=/data/Organization.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=Permission --file=/data/Permission.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=ProfileItem --file=/data/ProfileItem.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=Publisher --file=/data/Publisher.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=RelatedItems --file=/data/RelatedItems.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=RequestInfo --file=/data/RequestInfo.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;
           docker exec -i MyMongoDB mongoimport  --authenticationDatabase=admin --collection=SearchKeyword --file=/data/SearchKeyword.json  --uri="${{env.MONGODB_LOCAL_CONNECTION}}" ;

    - name: 10__MongoDB - Test access to Mongo database
      run: dotnet test ./api/Tests/CESMII.Marketplace.Tests.MongoDB/CESMII.Marketplace.Tests.MongoDB.csproj
      env:
         MARKETPLACE_MONGODB_CONNECTIONSTRING: ${{env.MONGODB_LOCAL_CONNECTION}}
         MARKETPLACE_MONGODB_DATABASE: ${{env.MONGODB_DATABASE_NAME}}

    - name: 11__MongoDB - Query Bridge Connection to MyMongoDB Container
      run:
         export TEMPIPVALUE=$(docker exec -i MyMongoDB hostname -i) ;
         echo "MONGODB_BRIDGE_CONNECTION=mongodb://testuser:password@$TEMPIPVALUE:27017" >> $GITHUB_ENV

    ############################################################
    # Run one of these two
    # Start Marketplace Container (On Github)
    - name: 12__Marketplace - Start the Container (On Github)
      if: env.ONGITHUB == 'true'
      run: |
           docker run -dt --name CESMII.Marketplace.API --network mysubnet1 -v "/home/runner/work/Marketplace/Marketplace/api/CESMII.Marketplace.API:/app" -v "/home/runner/work/Marketplace/Marketplace:/src/" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_ENVIRONMENT=Development" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "EnableCloudLibSearch=false" -e "ASPNETCORE_URLS=http://+:80" -e "MARKETPLACE_GITHUB_WORKFLOW_COMMANDS=true" -e "MARKETPLACE_MONGODB_CONNECTIONSTRING=${{env.MONGODB_BRIDGE_CONNECTION}}" -e "MARKETPLACE_MONGODB_DATABASE=test" -p 5000:80  --entrypoint tail cesmiimarketplaceapi:dev -f /dev/null

    # Start Marketplace Container (On Desktop)
    - name: 13__Marketplace - Start the Container (On Desktop)
      if: env.ONGITHUB == 'false'
      run: |
           docker run -dt --name CESMII.Marketplace.API --network mysubnet1 -v "C:\Users\paul\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\paul\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -v "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\TokenService.Proxy\linux-x64\net6.0:/TokenService.Proxy:ro" -v "C:\CESMII.github\Marketplace\api\CESMII.Marketplace.API:/app" -v "C:\CESMII.github\Marketplace:/src/" -v "C:\Users\paul\.nuget\packages\:/root/.nuget/fallbackpackages" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=http://+:80" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "NUGET_PACKAGES=/root/.nuget/fallbackpackages" -e "NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages" -e "EnableCloudLibSearch=false" -e "MARKETPLACE_GITHUB_WORKFLOW_COMMANDS=true" -e "MARKETPLACE_MONGODB_CONNECTIONSTRING=${{env.MONGODB_BRIDGE_CONNECTION}}" -e "MARKETPLACE_MONGODB_DATABASE=test" -p 5000:80 --entrypoint tail cesmiimarketplaceapi:dev -f /dev/null

    ############################################################


    ############################################################
    # Run one of these two
    # Start the Main Dll in the Container (On Github)
    ##  Github can accommodate "docker exec -i.... & ", ampersand at the end!!!)
    ##  In Windows, docker exec -id works better
    - name: 14__Marketplace - Start the Main Dll in the Container (Github)
      if: env.ONGITHUB == 'true'
      run: |
        docker exec -di  -e "MARKETPLACE_MONGODB_CONNECTIONSTRING=${{env.MONGODB_BRIDGE_CONNECTION}}" -e "MARKETPLACE_MONGODB_DATABASE=test" CESMII.Marketplace.API dotnet /src/publish/CESMII.Marketplace.API.dll
    
    # Start the Main Dll in the Container (On the Desktop)
    - name: 15__Marketplace - Start the Main Dll in the Container (Desktop)
      if: env.ONGITHUB == 'false'
      run: |
        docker exec -di  -e "MARKETPLACE_MONGODB_CONNECTIONSTRING=${{env.MONGODB_BRIDGE_CONNECTION}}" -e "MARKETPLACE_MONGODB_DATABASE=test" CESMII.Marketplace.API dotnet /src/publish/CESMII.Marketplace.API.dll
    ############################################################


    # Testing -- Call into Marketplace Rest Api from runner
    - name: 16__Test-Marketplace - Rest API Basic Test
      if: always()
      run: dotnet test -e "MARKETPLACE_URL1=http://localhost:5000/api" ./api/Tests/CESMII.Marketplace.Tests.RestApi/CESMII.Marketplace.Tests.RestApi.csproj

    - name: 17__Networking - Query Bridge Connection to CESMII.Marketplace.API Container
      run:
         export TEMPIPVALUE=$(docker exec -i CESMII.Marketplace.API hostname -i) ;
         echo "MARKETPLACE_BRIDGE_CONNECTION=http://$TEMPIPVALUE" >> $GITHUB_ENV

    # Start NodeJS using port 5000 to access the API
    # If there are any places where port 80 is needed, we need to split that off somehow
    - name: 18__NodeJS - Create and Start Docker Container for frontend
      run: |
        docker build . -t cesmii-marketplace/node-web-app
        docker run -d --name=MyNodeJS -p 3000:3000 --network mysubnet1  -e "REACT_APP_BASE_API_URL=${{env.MARKETPLACE_BRIDGE_CONNECTION}}:5000/api" cesmii-marketplace/node-web-app npm run-script start-in-browser-test
      working-directory: ./frontend


    ############################################################
    # Run one of these two
    - name: 19__Selenium - Create container for selenium (Github)
      if: env.ONGITHUB == 'true'
      run: |
         docker run -d --name=MySelenium --network mysubnet1 --mount src="/home/runner/work/Marketplace/Marketplace",target=/src,type=bind -p 4444:4444 selenium/standalone-chrome

    - name: 20__Selenium - Create container for selenium (Desktop)
      if: env.ONGITHUB == 'false'
      run: |
         docker run -d --name=MySelenium --network mysubnet1 --mount src="C:/CESMII.github/Marketplace",target=/src,type=bind -p 4444:4444 selenium/standalone-chrome
    ############################################################

    - name: 21__Selenium - Dotnet SDK Prerequisites
      run:
        docker exec -i MySelenium sudo wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb ;
        docker exec -i MySelenium sudo dpkg -i packages-microsoft-prod.deb ;
        docker exec -i MySelenium sudo rm packages-microsoft-prod.deb

    - name: 22__Selenium - Dotnet SDK 6.0 Installation
      run:
        docker exec -i MySelenium sudo apt-get update ;
        docker exec -i MySelenium sudo apt-get install -y dotnet-sdk-6.0

    - name: 23__Networking - Query Bridge Connection to NodeJS (FrontEnd)
      run:
         export TEMPIPVALUE=$(docker exec -i MyNodeJS hostname -i) ;
         echo "NODEJS_BRIDGE_CONNECTION=http://$TEMPIPVALUE" >> $GITHUB_ENV
    

    - name: 24__In-Browser Testing - Integrity of Marketplace Web Page
      if: always()
      run: docker exec -i --workdir /src/api/Tests/CESMII.MP.Tests.InBrowser.WebPages MySelenium sudo dotnet test -e NODEJS=${{env.NODEJS_BRIDGE_CONNECTION}} CESMII.MP.Tests.InBrowser.WebPages.csproj # > /Test_Results_Marketplace_Web_Page.txt


    # - name: 25__In-Browser Testing - Integrity of Marketplace Web Page - Display Test Results
    #   if: always()
    #   run: /usr/share/dotnet/dotnet run --project IgnoreLinesWith.csproj /Test_Results_Marketplace_Web_Page.txt "Cannot assign requested address" "Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe." "Only local connections are allowed."
    #   working-directory: /mnt/c/CESMII.github/Marketplace/api/Tests/Helpers/IgnoreLinesWith


    - name: 26__In-Browser Testing - Library Searches
      if: always()
      run: docker exec -i --workdir /src/api/Tests/CESMII.MP.Tests.InBrowser.LibrarySearch MySelenium sudo dotnet test -e NODEJS=${{env.NODEJS_BRIDGE_CONNECTION}} CESMII.MP.Tests.InBrowser.LibrarySearch.csproj # > /Test_Results_Library_Searches.txt


    # - name: 27__In-Browser Testing - Library Searches - Display Test Results
    #   if: always()
    #   run: /usr/share/dotnet/dotnet run --project IgnoreLinesWith.csproj /Test_Results_Library_Searches.txt "Cannot assign requested address" "Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe." "Only local connections are allowed."
    #   working-directory: /mnt/c/CESMII.github/Marketplace/api/Tests/Helpers/IgnoreLinesWith
  
